---

version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    debug:
        format: "%(filename)s:%(lineno)d : %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: debug
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO            
        formatter: debug
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR            
        formatter: debug
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    requests:
        level: WARNING
        handlers: [console]
        propagate: no
    executor:
        level: WARNING
        handlers: [console]
        propagate: no
    urllib3:
        level: WARNING
        handlers: [console]
        propagate: no
    elastic:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
